### ISSUE TITLE
RootTools no activity found to handle intent

### ISSUE THREAD

**Issue by ITanCh** [j4velin/SystemAppMover#13]
```
// CRASH: de.j4velin.systemappmover (pid 4549)
// Short Msg: android.content.ActivityNotFoundException
// Long Msg: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=market://details?id=stericson.busybox }
// Build Label: Android/aosp_flo/flo:6.0.1/MOB30P/tianchi10041651:userdebug/test-keys
// Build Changelist: eng.tianchi.20161004.165046
// Build Time: 1475571199000
// android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=market://details?id=stericson.busybox }
// 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1798)
// 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1512)
// 	at android.app.Activity.startActivityForResult(Activity.java:3930)
// 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
// 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:334)
// 	at android.app.Activity.startActivityForResult(<Xposed>)
// 	at android.app.Activity.startActivityForResult(Activity.java:3890)
// 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
// 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:334)
// 	at android.app.Activity.startActivityForResult(<Xposed>)
// 	at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:820)
// 	at android.app.Activity.startActivity(Activity.java:4213)
// 	at android.app.Activity.startActivity(Activity.java:4181)
// 	at com.stericson.RootTools.internal.RootToolsInternalMethods.offerBusyBox(RootToolsInternalMethods.java:1369)
// 	at com.stericson.RootTools.RootTools.offerBusyBox(RootTools.java:587)
// 	at de.j4velin.systemappmover.MoverActivity$6$2$2.onClick(MoverActivity.java:210)
// 	at android.view.View.performClick(View.java:5204)
// 	at android.view.View$PerformClick.run(View.java:21153)
// 	at android.os.Handler.handleCallback(Handler.java:739)
// 	at android.os.Handler.dispatchMessage(Handler.java:95)
// 	at android.os.Looper.loop(Looper.java:148)
// 	at android.app.ActivityThread.main(ActivityThread.java:5417)
// 	at java.lang.reflect.Method.invoke(Native Method)
// 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
// 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
// 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
//
````

**Comment by ITanCh** [comment]
Thanks 👍
